// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWgMht3SqwyWGF7mSZbwymTk8PsEKyjR0',
    appId: '1:187733989912:web:09be00285b53091d9d816d',
    messagingSenderId: '187733989912',
    projectId: 'apptouripi',
    authDomain: 'apptouripi.firebaseapp.com',
    storageBucket: 'apptouripi.firebasestorage.app',
    measurementId: 'G-QP5QYDJZ2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiMW_u1JUG5KXk_xqtgtyiDV6Kq4wBiHE',
    appId: '1:187733989912:android:d880392f62ad8ca99d816d',
    messagingSenderId: '187733989912',
    projectId: 'apptouripi',
    storageBucket: 'apptouripi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQZF1u67G4YSivqyVBH-gFIc5vumYV6G8',
    appId: '1:187733989912:ios:a63a5fbba09e725f9d816d',
    messagingSenderId: '187733989912',
    projectId: 'apptouripi',
    storageBucket: 'apptouripi.firebasestorage.app',
    iosBundleId: 'com.example.ipiDeliTour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQZF1u67G4YSivqyVBH-gFIc5vumYV6G8',
    appId: '1:187733989912:ios:a63a5fbba09e725f9d816d',
    messagingSenderId: '187733989912',
    projectId: 'apptouripi',
    storageBucket: 'apptouripi.firebasestorage.app',
    iosBundleId: 'com.example.ipiDeliTour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWgMht3SqwyWGF7mSZbwymTk8PsEKyjR0',
    appId: '1:187733989912:web:cd813c2151cafde69d816d',
    messagingSenderId: '187733989912',
    projectId: 'apptouripi',
    authDomain: 'apptouripi.firebaseapp.com',
    storageBucket: 'apptouripi.firebasestorage.app',
    measurementId: 'G-H13VD3N8LR',
  );
}
