// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWgMht3SqwyWGF7mSZbwymTk8PsEKyjR0',
    appId: '1:187733989912:web:09be00285b53091d9d816d',
    messagingSenderId: '187733989912',
    projectId: 'apptouripi',
    authDomain: 'apptouripi.firebaseapp.com',
    storageBucket: 'apptouripi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHfO7kZsj1RjkTKOvz3uyGhQBnBZHhfGo',
    appId: '1:187733989912:android:2f6ad274d613320b9d816d',
    messagingSenderId: '187733989912',
    projectId: 'apptouripi',
    storageBucket: 'apptouripi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo6G2WqQ_SJD4dYFXnTjGDH9lA5HTjEfc',
    appId: '1:187733989912:ios:a88e2df23e2c66c39d816d',
    messagingSenderId: '187733989912',
    projectId: 'apptouripi',
    storageBucket: 'apptouripi.firebasestorage.app',
    iosBundleId: 'com.example.ipiDeliTour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo6G2WqQ_SJD4dYFXnTjGDH9lA5HTjEfc',
    appId: '1:187733989912:macos:a88e2df23e2c66c39d816d',
    messagingSenderId: '187733989912',
    projectId: 'apptouripi',
    storageBucket: 'apptouripi.firebasestorage.app',
    iosBundleId: 'com.example.ipiDeliTour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWgMht3SqwyWGF7mSZbwymTk8PsEKyjR0',
    appId: '1:187733989912:windows:d08b0c7ce79b1b039d816d',
    messagingSenderId: '187733989912',
    projectId: 'apptouripi',
    storageBucket: 'apptouripi.firebasestorage.app',
  );
}